### ISSUE TITLE
auto-enumeration not supported in older versions of python3

### ISSUE THREAD

**Issue by Munksgaard** [pdemonaco/factorio-mod-updater#19]
I'm running python 3.4.2 on my server, and the module update script gives me the following error when I try to run it:

```
factorio@munksgaard:/opt/factorio$ ./mod-updater.py -s /opt/factorio/data/server-settings.json -m /opt/factorio/mods --fact-path /opt/factorio/bin/x64/factorio --update
Traceback (most recent call last):
  File "./mod-updater.py", line 12, in <module>
    from enum import Enum, auto
ImportError: cannot import name 'auto'
```

Apparently, `auto` was not added until python 3.6 (https://docs.python.org/3/library/enum.html). Is there a way to fix your script so that it works with older versions as well?

**Comment by pdemonaco** [comment]
@Munksgaard I'm closing this out as well per the commentary in #20.
