### ISSUE TITLE
can't update again

### ISSUE THREAD

**Issue by szentigrad3** [pdemonaco/factorio-mod-updater#9]
Factorio Release: 0.18

Retrieving metadata....................................................................................................complete!

Info: adding missing dependency angelsaddons-crawlertrain
Mod                                     Version Action          Result          Message
AutoDeconstruct                         0.1.17  Validate        Success
AutoTrash                               5.1.1   Validate        Success
BitersBegoneUpdated                     0.2.1   Validate        Success
Bottleneck                              0.11.3  Validate        Success
Clowns-AngelBob-Nuclear                 1.1.13  Validate        Success
Clowns-Extended-Minerals                1.1.11  Validate        Success
Clowns-Nuclear                          1.3.8   Validate        Success
Clowns-Processing                       1.3.10  Validate        Success
Clowns-Science                          1.0.18  Validate        Success
CopyAssemblerPipeDirection              0.1.3   Validate        Success
Crafting_Speed_Research                 0.2.2   Validate        Success
Cursed-BCR                              0.1.1   Validate        Success
Enhanced_Map_Colors                     1.5.1   Validate        Success
EvoGUI                                  0.4.501 Validate        Success
FARL                                    4.0.1   Validate        Success
Factorissimo2                           2.4.1   Validate        Success
Flow Control                            3.0.6   Validate        Success
InfiniteWorkerRobotCapacity_Research    0.1.51  skip            N/A             No release found for factorio '0.18', skipping update!
KitchsDynamicPersonalLighting           0.1.1   Validate        Success
LoaderRedux                             1.5.1   Validate        Success
Nanobots                                3.2.5   Validate        Success
OSHA_BotRecaller_patch                  0.1.0   Validate        Success
OpteraLib                               0.2.1   Validate        Success
PickerAtheneum                          1.2.0   Validate        Success
PickerBeltTools                         1.2.0   Validate        Success
PickerBlueprinter                       1.1.1   Validate        Success
PickerDollies                           1.1.1   Validate        Success
PickerEquipmentKeys                     1.1.0   Validate        Success
PickerExtended                          4.1.1   Validate        Success
PickerInventoryTools                    1.1.2   Validate        Success
PickerPipeTools                         1.1.0   Validate        Success
PickerTweaks                            2.2.1   Validate        Success
PickerVehicles                          1.1.0   Validate        Success
Robot_Battery_Research                  0.2.0   Validate        Success
ShinyAngelGFX                           0.18.2  Validate        Success
ShinyBobGFX                             0.18.3  Validate        Success
ShinyIcons                              0.18.1  Validate        Success
StoneWaterWell                          1.18.4  Validate        Success
TheFatController                        5.0.1   Validate        Success
TogglePeacefulMode                      0.1.5   Validate        Success
VehicleSnap                             1.18.1  Validate        Success
VoidChestPlus                           2.3.2   remove          Success
VoidChestPlus                           2.3.3   Download        Success         Updating from '2.3.2'
Warehousing                             0.3.0   Validate        Success
YARM                                    0.8.101 Validate        Success
alien-biomes                            0.5.2   Validate        Success
alien-biomes-hr-terrain                 0.5.1   Validate        Success
angelsaddons-crawlertrain               0.1.0   Download        Success         Downloading initial release
angelsbioprocessing                     0.7.6   Validate        Success
angelsindustries                        0.3.6   Validate        Success
angelsinfiniteores                      0.9.2   Validate        Success
angelspetrochem                         0.9.6   Validate        Success
angelsrefining                          0.11.8  Validate        Success
angelssmelting                          0.6.4   Validate        Success
auto-research-18                        5.1.1   Validate        Success
bobassembly                             0.18.4  Validate        Success
bobelectronics                          0.18.1  Validate        Success
bobenemies                              0.18.3  Validate        Success
bobequipment                            0.18.1  Validate        Success
bobgreenhouse                           0.18.0  Validate        Success
bobinserters                            0.18.1  Validate        Success
boblibrary                              0.18.5  Validate        Success
boblogistics                            0.18.7  Validate        Success
bobmining                               0.18.1  Validate        Success
bobmodules                              0.18.2  Validate        Success
bobores                                 0.18.2  Validate        Success
bobplates                               0.18.6  Validate        Success
bobpower                                0.18.5  Validate        Success
bobrevamp                               0.18.2  Validate        Success
bobtech                                 0.18.3  Validate        Success
bobvehicleequipment                     0.18.1  Validate        Success
bobwarfare                              0.18.4  Validate        Success
clock                                   0.18.0  Validate        Success
crafting_combinator                     0.15.2  Validate        Success
even-distribution                       0.3.17  Validate        Success
extendedangels                          0.3.3   Validate        Success
far-reach                               0.18.0  Validate        Success
fluid-void-extra                        1.4.1   Validate        Success
geothermalgen                           0.2.6   Validate        Success
helmod                                  0.10.14 Validate        Success
logistic-cargo-wagon                    0.18.2  Validate        Success
longer-belts-redux                      0.18.1  Validate        Success
manual-inventory-sort                   2.2.1   Validate        Success
mini-machines                           7.1.3   Validate        Success
miniloader                              1.11.0  remove          Success
miniloader                              1.11.1  Download        Success         Updating from '1.11.0'
omnilib                                 3.18.2  Validate        Success
omnimatter                              3.18.1  Validate        Success
omnimatter_crystal                      3.18.1  Validate        Failure
Traceback (most recent call last):
  File "/home/noidea/mod_updater.py", line 651, in <module>
    UPDATER.update()
  File "/home/noidea/mod_updater.py", line 472, in update
    self._download_latest_release(mod)
  File "/home/noidea/mod_updater.py", line 589, in _download_latest_release
    message=message)
UnboundLocalError: local variable 'message' referenced before assignment

**Comment by pdemonaco** [comment]
@szentigrad3 you're not using the updated release I pushed earlier toady. Please update and try again.

**Comment by szentigrad3** [comment]
i am using the update from today

**Comment by pdemonaco** [comment]
Oh, my apologies, the loss of formatting made me think it was the older form of output. I expected something similar to the following:
```bash
Factorio Release: 0.18

Retrieving metadata...............................................complete!

Mod                             Version Action          Result          Message
Bottleneck                      0.11.3  Validate        Success
Construction_Drones             0.4.9   Validate        Success
Crafting_Speed_Research         0.2.2   Validate        Success
FNEI                            0.3.0   Validate        Success
LoaderRedux                     1.5.1   Validate        Success
LogisticTrainNetwork            1.12.10 Validate        Success
MaxRateCalculator               3.2.32  Validate        Success
OpteraLib                       0.2.1   Validate        Success
RaiLuaLib                       0.2.3   remove          Success
RaiLuaLib                       0.2.4   Download        Success         Updating from '0.2.3'
ShinyAngelGFX                   0.18.2  Validate        Success
ShinyBobGFX                     0.18.3  Validate        Success
Squeak Through                  1.8.0   Validate        Success
Tapeline                        1.0.4   Validate        Success
Todo-List                       18.0.1  Validate        Success
VehicleSnap                     1.18.1  Validate        Success
angelsaddons-cab                0.2.0   Validate        Success
angelsaddons-crawlertrain       0.1.0   Validate        Success
angelsaddons-oresilos           0.6.0   Validate        Success
angelsaddons-petrotrain         0.5.3   Validate        Success
angelsaddons-pressuretanks      0.5.0   Validate        Success
angelsaddons-warehouses         0.5.0   Validate        Success
angelsbioprocessing             0.7.6   Validate        Success
angelsindustries                0.3.6   Validate        Success
angelsinfiniteores              0.9.2   Validate        Success
angelspetrochem                 0.9.6   Validate        Success
angelsrefining                  0.11.8  Validate        Success
angelssmelting                  0.6.4   Validate        Success
bobassembly                     0.18.4  Validate        Success
bobelectronics                  0.18.1  Validate        Success
bobenemies                      0.18.3  Validate        Success
bobgreenhouse                   0.18.0  Validate        Success
bobinserters                    0.18.1  Validate        Success
boblibrary                      0.18.5  Validate        Success
boblogistics                    0.18.7  Validate        Success
bobmining                       0.18.1  Validate        Success
bobmodules                      0.18.2  Validate        Success
bobores                         0.18.2  Validate        Success
bobplates                       0.18.6  Validate        Success
bobpower                        0.18.5  Validate        Success
bobrevamp                       0.18.2  Validate        Success
bobtech                         0.18.3  Validate        Success
bobvehicleequipment             0.18.1  Validate        Success
bobwarfare                      0.18.4  Validate        Success
even-distribution               0.3.17  Validate        Success
nixie-tubes                     0.18.2  Validate        Success
stdlib                          1.4.2   Validate        Success
textplates                      0.5.2   Validate        Success
```

Thanks for reporting the problem - I'll have a fix merged shortly.
